config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users
  resources :profiles
  resources :shapes
  resources :reviews
  resources :products

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
  belongs_to :profile, :optional => true
  belongs_to :shape, :optional => true

  # validates :model, uniqueness: {scope: [:year, :brand], message: "Snowboard Already Exists"}
  validates :model, uniqueness: { scope: [:year, :brand],
      message: " Already Exists" }

      # this is the pg_search gem
      #it also has the scope that creates the search method for both the products
      #and its associated tables
  include PgSearch::Model
  pg_search_scope :search_by_brand_model, against: [:brand, :model, :profile_id],
                  :associated_against => {:profile => :name, :shape => :name}

    # the name method combines three seperte inputs from the new product form
    # to generate a name that can be used elsewhere in the site
    def name
      "#{self.year} #{self.brand} #{self.model}"
    end
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :products
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product, :optional => true
  belongs_to :user, :optional => true
end

app/models/shape.rb
class Shape < ApplicationRecord
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_many :reviews

end

app/controllers/_controller.rb
class Controller < ApplicationController
  def Pages
  end

  def home
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @reviews = Review.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :check_for_login, :only => [:index]

  def index
    @products = Product.all
    #this method produces the search results on the product index.
    # if there are no results, it spits out an error message and loads Product.all
    if params[:query].present?
      search_results = Product.search_by_brand_model(params[:query])
      if search_results.empty?
       @products = Product.all
       @message = "No Results"
      else
        @products = search_results
      end
    end

  end


  def new
    @product = Product.new
  end
  def create
    @product = Product.create product_params
    if @product.save
      redirect_to new_review_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find params[:id]
  end
  def update
    product = Product.find params[:id]
    product.update product_params
    redirect_to product_path
  end

  def show
    @products = Product.find params[:id]
  end

  def destroy
    product = Product.find params[:id]
    product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:brand, :model, :year, :image, :name, :brief, :shape_id, :profile_id)

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :check_for_login, :only => [:new]
  def index
    redirect_to root_path
  end

  def new
    @review = Review.new
  end
  def create
    #need tob build create page.
    review = Review.create review_params
    redirect_to products_path
  end

  def edit
    @review = Review.find params[:id]
  end
  def update
    review = Review.find params[:id]
    review.update review_params
    redirect_to review_path
  end

  def show
    @review = Review.find params[:id]
  end

  def destroy
    review = Review.find params[:id]
    review.destroy
    redirect_to products_path
  end
  private
  def review_params
    params.require(:review).permit(:title, :author, :date, :rating, :brief, :product_id, :user_id)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/shapes_controller.rb
class ShapesController < ApplicationController
  before_action :check_for_admin, :only => [:new]
  def index
    @shapes = Shape.all
  end

  def new
    @shape = Shape.new
  end
  def create
    shape = Shape.create shape_params
    redirect_to shapes_path
  end

  def edit
    @shape = Shape.find params[:id]
  end
  def update
    shape = Shape.find params[:id]
    shape.update shape_params
    redirect_to shape_path
  end

  def show
    @shape = Shape.find params[:id]
  end
  def destroy
    shape = Shape.find params[:id]
    shape.destroy
    redirect_to shapes_path
  end

  private
  def shape_params
    params.require(:shape).permit(:name, :terrain, :image, :brief)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_login, :only => [:index]
  def new
    @user = User.new
  end
  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end
  def index
    @user = User.find @current_user.id

  end
  def show
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<% if @product.errors.any? %>
  <ol>
      <li><%= @product.errors.full_messages %></li>
  </ol>
<% end %>
<%= form_for @product do |f| %>
  <div class="form row">
    <div class="form-group col-md-2">
      <%= f.label :year %>
      <%= f.text_field :year, :class => 'form-control', :required => true %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :brand %>
      <%= f.text_field :brand, :class => 'form-control', :required => true %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :model %>
      <%= f.text_field :model, :class => 'form-control', :required => true %>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-4">
      <%= f.label :shape_id %>
      <%= f.select :shape_id, Shape.pluck(:name, :id), :include_blank => true, :required => true %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :profile_id %>
      <%= f.select :profile_id, Profile.pluck(:name, :id), :include_blank => true, :required => true%>
    </div>
    <div class="form-group col-md-4">
      <%= f.label 'Image URL' %>
      <%= f.url_field :image, :placeholder => 'https://...', :class => 'form-control', :required => true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Board Overview' %>
    <%= f.text_area :brief, :class => 'form-control', :required => true %>
  </div>
  <%= f.submit 'Create Board', :class => "btn btn-primary" %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Board</h1>

<%= render :partial => 'form' %>

app/views/products/index.html.erb
<h1>Snowboard List</h1>
<p><%= @message %></p>
<%= form_tag products_path, method: :get do %>
  <p id = 'search'>
    <%= text_field_tag :query, params[:query] , :placeholder => 'search list' %>
    <%= submit_tag "Search", :class => "btn btn-primary", name: nil %>
  </p>

<% end %>
<div class="row">
<% @products.each do |product| %>


  <div class="col-md-4">
    <div class="card mb-4">
      <div class="card-image-product fill">
        <img src="<%= product.image %>" class="card-img-top p-image " alt="...">
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= product.name %></h5>
        <%= link_to "View Board", "/products/#{ product.id }", :class => "btn btn-primary" %>
        <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
      </div>
    </div>
  </div>



<% end %>
</div>

app/views/products/new.html.erb
<h1>Add Product</h1>

<%= render :partial => 'form' %>

app/views/products/show.html.erb
<style media="screen">
  .jumbotron {
    background-image: url(<%= @products.image %>);
    background-size: contain;
    background-repeat: no-repeat;
    background-position: top right;
  }
  @media (max-width: 991px) {
    .jumbotron {
      background-image: none;
    }
    .product-wrap {
      display: inherit;
    }
    .col-md-6 {
      max-width: 100%;
    }
  }
  .review-card {

  }
  .review-card * {
    display: inline-block;
  }
  .media-body * {
    margin-right: 10px;
  }
  .review-head3 {
    display: inline-block;
    margin: 20px auto;
  }
</style>
<div class="product-wrap fill">
  <%= image_tag @products.image, :class => 'hero card-img-top' %>
</div>
<div class="jumbotron">
  <div class="col-md-6">
    <h2 class="display-4"><%= @products.name %></h2>

    <p class="lead"><%= @products.brief.truncate(150) %></p>
    <hr class="my-4">

    <p>Continue reading below.</p>

  </div>
</div>
<ul class="list-unstyled">
  <li class="media">
    <div class="media-body">
      <h3 class="mt-0 mb-1">Overview</h3>
      <h5>Board Shape: <%= link_to @products.shape.name, "/shapes/#{@products.shape.id}" %></h5>
      <h5>Board Profile: <%=link_to @products.profile.name, "/profiles/#{@products.profile.id}" %></h5>

      <p><%= @products.brief %></p>
    </div>
  </li>
</ul>
<hr class="my-4">
    <h3 class="review-head3">Board Reviews</h3>     <%= link_to "Add a Review", new_review_path %>

      <% @products.reviews.each do |review| %>
    <div class="review-row">


      <div class="review-card">


            <%# <%= link_to "View Review", "/reviews/#{review.id}", :class => "mr-3 btn btn-primary" %>
            <div class="media-body">
                <h5><%= link_to review.title, "/reviews/#{review.id}" %></h5>
              <p>Date Ridden: <%= review.date %></p><p>Author: <%= review.author %></p>

            </div>

      </div>

    </div>

      <% end %>
      <% if @current_user.present? && @current_user.admin?%>

        <div class="controls ">
          <%= link_to "Edit", edit_product_path %>
          |
          <%= link_to "Delete #{@products.name}", @products, :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
        </div>
        <% end %>

app/views/shapes/_form.html.erb
<% if @shape.errors.any? %>
  <ol>
      <li><%= @shape.errors.full_messages %></li>
  </ol>
<% end %>
<%= form_for @shape do |f| %>
  <div class="form row">
    <div class="form-group col-md-4">
      <%= f.label :name %>
      <%= f.text_field :name, :class => 'form-control', :required => true %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :terrain %>
      <%= f.text_field :terrain, :class => 'form-control', :required => true %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label 'Image URL' %>
      <%= f.url_field :image, :placeholder => 'https://...', :class => 'form-control', :required => true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label 'Shape Overview' %>
    <%= f.text_area :brief, :class => 'form-control', :required => true %>
  </div>
  <%= f.submit 'Create Shape', :class => "btn btn-primary" %>
<% end %>

app/views/shapes/edit.html.erb
<h1>Edit Shape</h1>

<%= render :partial => 'form' %>

app/views/shapes/index.html.erb
<h1>Board Shapes</h1>
<p>The shape of a snowboard can effect the ease of riding certain terrain, snow conditions and also various riding styles. As snowboarding has developed as a sport </p>

<div class="row">
<% @shapes.each do |shape| %>


  <div class="col-md-4">
    <div class="card mb-4">
      <div class="card-image fill">
        <img src="<%= shape.image %>" class="card-img-top" alt="...">
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= shape.name %></h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <%= link_to "View Shape", shape, :class => "btn btn-primary" %>
        <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
      </div>
    </div>
  </div>



<% end %>
</div>

app/views/shapes/new.html.erb
<h1>New Shape</h1>


<%= render :partial => 'form' %>

app/views/shapes/show.html.erb
<div class="wrap">
  <div class="hero-wrap fill">
    <%= image_tag @shape.image, :class => 'hero card-img-top' %>
  </div>

  <h2 class="display-4"><%= @shape.name %></h2>
  <h2 class="display-5">Terrain: <%= @shape.terrain %></h2>
  <p><%= @shape.brief %></p>
</div>

<% if @current_user.present? %>
  <% if @current_user.admin? %>
  <div class="controls ">
    <%= link_to "Edit", edit_shape_path %>
    <%= link_to "Delete #{@shape.name}", @shape, :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
  </div>
  <% end %>
  <% end %>

app/views/users/index.html.erb
<h1>my reviews</h1>

  <% @user.reviews.each do |review| %>
    <p><%= link_to review.title, "/reviews/#{review.id}" %></p>
  <% end %>

app/views/users/new.html.erb
<style media="screen">

</style>

<div class="wrapper-log">
  <h1>Sign Up</h1>
  <% if @user.errors.any? %>
    <ol>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ol>
  <% end %>
  <%= form_for @user do |f| %>
  <div class="form-group">
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= f.label :email, :required => true%>
        <%= f.email_field :email, :required => true, :class => 'form-control' %>
      </div>
      <div class="form-group col-md-6">
        <%= f.label :username, :required => true%>
        <%= f.text_field :username, :required => true, :class => 'form-control' %>
      </div>
      <div class="form-group col-md-6">
        <%= f.label :password %>
        <%= f.password_field :password, :class => 'form-control' %>
      </div>
      <div class="form-group col-md-6">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, :class => 'form-control' %>
      </div>

        <%= f.submit 'Sign Up', :class => 'btn btn-primary' %>
      <% end %>

      </div>
    </div>
</div>