config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users
  resources :profiles
  resources :shapes
  resources :reviews
  resources :products

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
  belongs_to :profile, :optional => true
  belongs_to :shape, :optional => true

  # validates :model, uniqueness: {scope: [:year, :brand], message: "Snowboard Already Exists"}
  validates :model, uniqueness: { scope: [:year, :brand],
      message: " Already Exists" }

      # this is the pg_search gem
      #it also has the scope that creates the search method for both the products
      #and its associated tables
  include PgSearch::Model
  pg_search_scope :search_by_brand_model, against: [:brand, :model, :profile_id],
                  :associated_against => {:profile => :name, :shape => :name}

    # the name method combines three seperte inputs from the new product form
    # to generate a name that can be used elsewhere in the site
    def name
      "#{self.year} #{self.brand} #{self.model}"
    end
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :products
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product, :optional => true
  belongs_to :user, :optional => true
end

app/models/shape.rb
class Shape < ApplicationRecord
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_many :reviews

end

app/controllers/_controller.rb
class Controller < ApplicationController
  def Pages
  end

  def home
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @reviews = Review.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :check_for_login, :only => [:new]
  def index
    redirect_to root_path
  end

  def new
    @review = Review.new
  end
  def create
    #need tob build create page.
    review = Review.create review_params
    redirect_to products_path
  end

  def edit
    @review = Review.find params[:id]
  end
  def update
    review = Review.find params[:id]
    review.update review_params
    redirect_to review_path
  end

  def show
    @review = Review.find params[:id]
  end

  def destroy
    review = Review.find params[:id]
    review.destroy
    redirect_to products_path
  end
  private
  def review_params
    params.require(:review).permit(:title, :author, :date, :rating, :brief, :product_id, :user_id)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/shapes_controller.rb
class ShapesController < ApplicationController
  before_action :check_for_admin, :only => [:new]
  def index
    @shapes = Shape.all
  end

  def new
    @shape = Shape.new
  end
  def create
    shape = Shape.create shape_params
    redirect_to shapes_path
  end

  def edit
    @shape = Shape.find params[:id]
  end
  def update
    shape = Shape.find params[:id]
    shape.update shape_params
    redirect_to shape_path
  end

  def show
    @shape = Shape.find params[:id]
  end
  def destroy
    shape = Shape.find params[:id]
    shape.destroy
    redirect_to shapes_path
  end

  private
  def shape_params
    params.require(:shape).permit(:name, :terrain, :image, :brief)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_login, :only => [:index]
  def new
    @user = User.new
  end
  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end
  def index
    @user = User.find @current_user.id

  end
  def show
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>

<div class="form-group" data-intro = "Give your new review a title!">
  <%= f.label :title %>
  <%= f.text_field :title, :required => true, :autofocus => true, :class => 'form-control' %>

</div>
<div class="form-row">
    <div class="form-group col-md-6" data-intro = "Add the board you want to review!">
      <%= f.label "Select a Board" %>
        <%= f.select :product_id, Product.all.map{ |p| [p.name, p.id]}, :include_blank => true, :required => true %>
        <div data-intro = "If you can't find the Board you want to review, add it to our site!">
          <%= link_to 'Add Board', new_product_path, :id => 'add-board'  %>
        </div>
    </div>
    <div class="form-group col-md-4" data-intro = "When did you test the Board?">
      <%= f.label :date %>
      <input class="form-control" type="date" name="date" value="">
    </div>
    <div class="form-group col-md-2" data-intro = "Give the board a Rating out of 5">
      <%= f.label 'Rating' %>
      <%= f.number_field :rating, :class => 'form-control', :max => '5' %>
    </div>
  </div>
<div class="form-group" data-intro = "Provide a brief review on the board. This can include pros, cons, conditions and more!">
  <%= f.label :brief %>
  <%= f.text_area :brief, :class => 'form-control' %>
</div>
  <%= f.text_field :user_id, :value => @current_user.id, :type => 'hidden' %>
  <%= f.text_field :author, :value => @current_user.username, :type => 'hidden' %>

  <%= f.submit 'Submit Review', :class => "btn btn-primary" %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render :partial => 'form' %>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Add Review</h1>

<%= render :partial => 'form' %>

<script type="text/javascript">
  introJs().start();

</script>

app/views/reviews/show.html.erb
<style media="screen">
  .top {
    margin: 2rem auto;
  }
</style>
<div class="wrap">
  <h1><%= @review.title %></h1>
  <div class="top">
    <h4>Visit Snowboard: <%= link_to "here" ,"/products/#{@review.product_id}" %></h4>
    <h4>Author: <%= @review.author %></h4>
    <h4>Date Ridden: <%= @review.date %></h4>
    <h4>Rating: <%= @review.rating %>/5</h4>
  </div>

    <p><%= @review.brief %></p>


  <% if @current_user.present? && @current_user.id == @review.user_id%>
  <div class="controls">
    <%= link_to "Edit Review", edit_review_path %>
    |
    <%= link_to "Delete", @review, :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
  </div>
  <% end %>
</div>

app/views/session/new.html.erb
<div class="wrapper-log">
  <div class="form-group">
    <div class="form ">
      <h1>Log In</h1>

      <% if flash[:error].present? %>
        <p><%= flash[:error] %></p>
      <% end  %>
      <%# Use a form tag when its not a CRUD system %>

      <%= form_tag login_path do %>
      <div class="form-group ">
        <%= label_tag :email %>
        <%= email_field_tag :email, nil, :class => 'form-control' %>
      </div>
      <div class="form-group ">
        <%= label_tag :password %>
        <%= password_field_tag :password, nil, :class => 'form-control' %>
      </div>

        <%= submit_tag 'Sign In', :class => 'btn btn-primary' %>
      <% end %>

    </div>
  </div>

</div>