config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users
  resources :profiles
  resources :shapes
  resources :reviews
  resources :products

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
  belongs_to :profile, :optional => true
  belongs_to :shape, :optional => true

  # validates :model, uniqueness: {scope: [:year, :brand], message: "Snowboard Already Exists"}
  validates :model, uniqueness: { scope: [:year, :brand],
      message: " Already Exists" }

      # this is the pg_search gem
      #it also has the scope that creates the search method for both the products
      #and its associated tables
  include PgSearch::Model
  pg_search_scope :search_by_brand_model, against: [:brand, :model, :profile_id],
                  :associated_against => {:profile => :name, :shape => :name}

    # the name method combines three seperte inputs from the new product form
    # to generate a name that can be used elsewhere in the site
    def name
      "#{self.year} #{self.brand} #{self.model}"
    end
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :products
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product, :optional => true
  belongs_to :user, :optional => true
end

app/models/shape.rb
class Shape < ApplicationRecord
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_many :reviews

end

app/controllers/_controller.rb
class Controller < ApplicationController
  def Pages
  end

  def home
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @reviews = Review.all
  end
end

app/controllers/shapes_controller.rb
class ShapesController < ApplicationController
  before_action :check_for_admin, :only => [:new]
  def index
    @shapes = Shape.all
  end

  def new
    @shape = Shape.new
  end
  def create
    shape = Shape.create shape_params
    redirect_to shapes_path
  end

  def edit
    @shape = Shape.find params[:id]
  end
  def update
    shape = Shape.find params[:id]
    shape.update shape_params
    redirect_to shape_path
  end

  def show
    @shape = Shape.find params[:id]
  end
  def destroy
    shape = Shape.find params[:id]
    shape.destroy
    redirect_to shapes_path
  end

  private
  def shape_params
    params.require(:shape).permit(:name, :terrain, :image, :brief)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_login, :only => [:index]
  def new
    @user = User.new
  end
  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end
  def index
    @user = User.find @current_user.id

  end
  def show
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/assets/intro.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="/assets/intro.js">

    </script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>

      <header>
        <!-- bg-dark -->
        <nav class="navbar navbar-expand-md navbar-dark  fixed-top">
          <!-- <a href="#" class="navbar-brand" >Board Files</a> -->
          <%= link_to "Board Files", root_path, :class => 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Products", products_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Profiles", profiles_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Shapes", shapes_path, :class => "nav-link" %>
          </li>
          <% if @current_user.present? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">User Profile</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <%= link_to "Add Review", new_review_path, :class => "dropdown-item" %>
              <%= link_to "My Reviews", users_path, :class => "dropdown-item" %>
            <% if @current_user.admin? %>
            <div class="dropdown-divider"></div>

              <%= link_to "Add Shape", new_shape_path, :class => "dropdown-item" %>
              <%= link_to "Add Profile", new_profile_path, :class => "dropdown-item" %>
            <% end %>

            </div>

          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to  @current_user.username, '#', :class => "nav-link disabled" %>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", login_path, :method => 'delete', :class => "nav-link"  %>
            </li>
          </ul>

          <% else %>

        </ul>
        <form class="form-inline my-2 my-lg-0">
          <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <%= link_to "Sign Up", new_user_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log In", login_path, :class => "nav-link" %>
          </li>
          </ul>
          <% end %>
        </form>
        </div>
        </nav>
      </header>
<div class="container">
      <%= yield %>
  </div>

  </body>
</html>

app/views/pages/home.html.erb
<style media="screen">
  .landing-link {
    display: inline-block;
    margin: 1rem;
    text-decoration: none;
  }
  .landing-link a {
    color: white;

  }
  .landing-controls {
    margin: 1rem;
    text-align: center;

  }
</style>
<div class="wrap" >
  <h1>the Board files</h1>

  <h3>What are the board files?</h3>

  <p>It can be hard to understand the intricacies of snowboard design. Yes the design is important and looking cool gives you that warmy fuzzy feeling inside. But that feeling won't be there when suddenly you're on your arse and losing that arm wrestle between you and your equipment.</p>
  <p>That's right! Sometimes it is your equipment, not you, that means you can't turn that be harder, or spin that bit easier. Why am i sinking is half a metre of snow? Maybe it's me?</p>
  <p>Most of the time, it can be a lack of eperience, but did you ever consider maybe a little more goes into how a board is designed than that pretty design on the bottom of your board that no one will ever see?</p>
  <hr class="my-4">

  <h4>Here are two key features that, believe it or not, make certain styles of riding easier, or are genuinely effected by the riders experience and intention.</h4>
  <div class="landing-controls introduction-farm">
    <h5 class="landing-link btn btn-primary"><%= link_to 'Snowboard Profiles', profiles_path %></h5>
    <h5 class="landing-link btn btn-primary"><%= link_to 'Snowboard Shapes', shapes_path %></h5>
  </div>


</div>

<script type="text/javascript">
  introJs().start();

</script>